language: python
python: 3.6
cache: pip
env:
  - REPO_NAME="${PWD##*/}"
  - LAMBDA_BUCKET="essentials-awss3lambdaartifactsbucket-x29ftznj6pqw"
  - CFN_BUCKET="bootstrap-awss3cloudformationbucket-19qromfd235z9"
install:
  - pip install pipenv
  - pipenv install --dev
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - ./setup_aws_cli.sh || travis_terminate 1
  - export SAM_CLI_TELEMETRY=0
stages:
  - name: validate
  - name: deploy
    if: (tag =~ ^v) OR (branch = master AND type = push)
jobs:
  fast_finish: true
  include:
    - stage: validate
      script:
        - pre-commit run --all-files
        - sam build
#        - python -m pytest tests/ -v
    - stage: deploy
      script:
        - sam build
        - |
          sam package --template-file .aws-sam/build/template.yaml \
            --s3-bucket $LAMBDA_BUCKET \
            --output-template-file .aws-sam/build/$REPO_NAME.yaml
        - sam publish --template .aws-sam/build/$REPO_NAME.yaml
        - aws s3 cp .aws-sam/build/$REPO_NAME.yaml s3://$CFN_BUCKET/$REPO_NAME/$TRAVIS_BRANCH/
        - aws s3 cp s3-synapse-sync-bucket.j2 s3://$CFN_BUCKET/$REPO_NAME/$TRAVIS_BRANCH/
        - aws s3 cp s3-synapse-sync-kms-key.yaml s3://$CFN_BUCKET/$REPO_NAME/$TRAVIS_BRANCH/
